layout_spectrum: 0.9318997
typography_spectrum: 0.5801977
color:
  saturation: 0.8136201
  lightness: 0.5824373
  brandStrength: 0.6344086
  brandColors:
    - '#030202'
    - '#FBFBFA'
    - '#154A88'
    - '#D7C678'
    - '#C72720'
  rhythmicContrast: 0.8333333
name: Thinkings
